/**
 * Twilio Access Token Handler
 * 
 * This function returns the JWT token generated by your Python backend.
 * Run twilio_token_generator.py to get a fresh token, then paste it below.
 */
export const generateTwilioToken = async (): Promise<string> => {
  try {
    // STEP 1: Replace this with the JWT token from your Python script
    // Run: python twilio_token_generator.py
    // Then copy the generated token and paste it here:
    const jwtToken: string = "eyJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJTSzFmODAwNDZhYWZlNWJhNDJkMzIzMGI3ZDAwYzhlMTFmLTE3NTc0MDEzMTgiLCJncmFudHMiOnsidm9pY2UiOnsiaW5jb21pbmciOnsiYWxsb3ciOnRydWV9LCJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUGE1ZmVlODkyYWM5OGZkZmI4ZmQ4ZDBiYTRlYjA3YjRhIn19LCJpZGVudGl0eSI6InVzZXJfMTIzIn0sImlzcyI6IlNLMWY4MDA0NmFhZmU1YmE0MmQzMjMwYjdkMDBjOGUxMWYiLCJleHAiOjE3NTc0MDQ5MTgsIm5iZiI6MTc1NzQwMTMxOCwic3ViIjoiQUM2MWJlODlmNjMzMzNiNzQ4ODU4Zjk2NzFmZWVmMjZkNSJ9.9WsiabIUEo2IOuMTPmiqENwOzmk-2-i4tq01eTi_Ufg";
    
    // Validation
    if (!jwtToken || jwtToken === "eyJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJTSzFmODAwNDZhYWZlNWJhNDJkMzIzMGI3ZDAwYzhlMTFmLTE3NTc0MDEzMTgiLCJncmFudHMiOnsidm9pY2UiOnsiaW5jb21pbmciOnsiYWxsb3ciOnRydWV9LCJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUGE1ZmVlODkyYWM5OGZkZmI4ZmQ4ZDBiYTRlYjA3YjRhIn19LCJpZGVudGl0eSI6InVzZXJfMTIzIn0sImlzcyI6IlNLMWY4MDA0NmFhZmU1YmE0MmQzMjMwYjdkMDBjOGUxMWYiLCJleHAiOjE3NTc0MDQ5MTgsIm5iZiI6MTc1NzQwMTMxOCwic3ViIjoiQUM2MWJlODlmNjMzMzNiNzQ4ODU4Zjk2NzFmZWVmMjZkNSJ9.9WsiabIUEo2IOuMTPmiqENwOzmk-2-i4tq01eTi_Ufg") {
      throw new Error(`🔑 JWT Token Required!\n\nTo fix this:\n1. Update your credentials in twilio_token_generator.py\n2. Run: python twilio_token_generator.py\n3. Copy the generated JWT token\n4. Paste it in src/lib/twilioTokenGenerator.ts\n5. Save and refresh the page`);
    }

    // Basic JWT format validation
    const tokenParts = jwtToken.split('.');
    if (!jwtToken.includes('.') || tokenParts.length !== 3) {
      throw new Error('Invalid JWT token format. Please generate a new token using the Python script.');
    }

    console.log('✅ Using JWT token for Twilio authentication');
    return jwtToken;
    
  } catch (error) {
    console.error('❌ Token generation failed:', error);
    throw error;
  }
};
